# Generated by Django 3.0.5 on 2020-10-28 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projects.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('company_name', models.CharField(default='', max_length=100)),
                ('company_id', models.CharField(default='', max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=1000)),
                ('cost', models.DecimalField(decimal_places=0, max_digits=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Designs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('designer_name', models.CharField(max_length=200)),
                ('designer_lastname', models.CharField(max_length=200)),
                ('designer_email', models.EmailField(max_length=254)),
                ('design_state', models.CharField(choices=[('EN_PROCESO', 'En Proceso'), ('DISPONIBLE', 'Disponible')], max_length=15)),
                ('desing_original', models.ImageField(upload_to=projects.models.PathAndRename('designs/original'), validators=[projects.models.ResolutionAndType(800, 600)])),
                ('desing_converted', models.ImageField(blank=True, upload_to=projects.models.PathAndRename('designs/converted'))),
                ('design_price', models.DecimalField(decimal_places=0, max_digits=100)),
                ('created_at', models.DateTimeField(editable=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Projects')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
