# Generated by Django 3.1.1 on 2020-10-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designs',
            name='processing_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designs',
            name='processing_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designs',
            name='design_state',
            field=models.CharField(choices=[('EN_PROCESO', 'En Proceso'), ('DISPONIBLE', 'Disponible'), ('PENDIENTE', 'Pendiente'), ('ERROR_CONVERSION', 'Error Conversion')], max_length=20),
        ),
    ]
